name: sbnz
services:
  mysql:
    image: mysql:8.0
    container_name: sbnz_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'sbnzDB'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password123'
      LANG: 'en_US.UTF-8'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    ports:
      - '3306:3306'
    volumes:
      - sbnz_volume:/var/lib/mysql

volumes:
  sbnz_volume: